//
//  UIDocumentPickerExtensionViewController+TFEasyCoder.m
//  TFEasyCoder
//
//  Created by ztf on 16/10/26.
//  Copyright © 2016年 ztf. All rights reserved.
//

#import "UIDocumentPickerExtensionViewController+TFEasyCoder.h"
#import "NSObject+TFExecute.h"

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"


@implementation UIDocumentPickerExtensionViewController (TFEasyCoder)

TF_EC_MSTATIC_IMP(UIDocumentPickerExtensionViewController, UIDocumentPickerExtensionViewController *);
TF_EC_MINSTANCE_IMP(UIDocumentPickerExtensionViewController, UIDocumentPickerExtensionViewController *);





//superclass pros UIViewController
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,UITabBarItem *,tabBarItem)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,BOOL,hidesBottomBarWhenPushed)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,id<UIViewControllerTransitioningDelegate>  ,transitioningDelegate)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,UIView *,view)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,NSString *,title)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,BOOL,definesPresentationContext)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,BOOL,providesPresentationContextTransitionStyle)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,long long,modalTransitionStyle)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,long long,modalPresentationStyle)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,BOOL,modalPresentationCapturesStatusBarAppearance)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,BOOL,wantsFullScreenLayout)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,unsigned long long,edgesForExtendedLayout)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,BOOL,extendedLayoutIncludesOpaqueBars)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,BOOL,automaticallyAdjustsScrollViewInsets)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,CGSize,preferredContentSize)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,CGSize,contentSizeForViewInPopover)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,BOOL,modalInPopover)
//superclass pros UIResponder
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,NSUserActivity *,userActivity)
//superclass pros NSObject
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,NSArray *,accessibilityElements)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,NSArray *,accessibilityCustomActions)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,BOOL,isAccessibilityElement)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,NSString *,accessibilityLabel)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,NSString *,accessibilityHint)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,NSString *,accessibilityValue)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,unsigned long long,accessibilityTraits)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,UIBezierPath *,accessibilityPath)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,CGPoint,accessibilityActivationPoint)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,NSString *,accessibilityLanguage)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,BOOL,accessibilityElementsHidden)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,BOOL,accessibilityViewIsModal)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,BOOL,shouldGroupAccessibilityChildren)
TF_EC_CHAIN_PROP_IMP(UIDocumentPickerExtensionViewController ,long long,accessibilityNavigationStyle)





TF_EC_CHAIN_VALUEKYE_IMP(UIDocumentPickerExtensionViewController);


@end
