//
//  UIDocumentPickerExtensionViewController+TFEasyCoder.h
//  TFEasyCoder
//
//  Created by ztf on 16/10/26.
//  Copyright © 2016年 ztf. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import "TFEasyCoderConst.h"

TF_EC_BLOCK(UIDocumentPickerExtensionViewController,UIDocumentPickerExtensionViewController *);

@interface UIDocumentPickerExtensionViewController (TFEasyCoder)

TF_EC_MSTATIC_INT(UIDocumentPickerExtensionViewController, UIDocumentPickerExtensionViewController *);
TF_EC_MINSTANCE_INT(UIDocumentPickerExtensionViewController,UIDocumentPickerExtensionViewController *);





//superclass pros UIViewController
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,UITabBarItem *,tabBarItem)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,BOOL,hidesBottomBarWhenPushed)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,id<UIViewControllerTransitioningDelegate>  ,transitioningDelegate)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,UIView *,view)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,NSString *,title)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,BOOL,definesPresentationContext)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,BOOL,providesPresentationContextTransitionStyle)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,long long,modalTransitionStyle)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,long long,modalPresentationStyle)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,BOOL,modalPresentationCapturesStatusBarAppearance)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,BOOL,wantsFullScreenLayout)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,unsigned long long,edgesForExtendedLayout)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,BOOL,extendedLayoutIncludesOpaqueBars)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,BOOL,automaticallyAdjustsScrollViewInsets)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,CGSize,preferredContentSize)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,CGSize,contentSizeForViewInPopover)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,BOOL,modalInPopover)
//superclass pros UIResponder
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,NSUserActivity *,userActivity);
//superclass pros NSObject
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,NSArray *,accessibilityElements)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,NSArray *,accessibilityCustomActions)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,BOOL,isAccessibilityElement)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,NSString *,accessibilityLabel)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,NSString *,accessibilityHint)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,NSString *,accessibilityValue)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,unsigned long long,accessibilityTraits)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,UIBezierPath *,accessibilityPath)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,CGPoint,accessibilityActivationPoint)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,NSString *,accessibilityLanguage)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,BOOL,accessibilityElementsHidden)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,BOOL,accessibilityViewIsModal)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,BOOL,shouldGroupAccessibilityChildren)
TF_EC_CHAIN_PROP_INT(UIDocumentPickerExtensionViewController ,long long,accessibilityNavigationStyle)





@end