//
//  UIReferenceLibraryViewController+TFEasyCoder.m
//  TFEasyCoder
//
//  Created by ztf on 16/10/26.
//  Copyright © 2016年 ztf. All rights reserved.
//

#import "UIReferenceLibraryViewController+TFEasyCoder.h"
#import "NSObject+TFExecute.h"

@implementation UIReferenceLibraryViewController (TFEasyCoder)

TF_EC_MSTATIC_IMP(UIReferenceLibraryViewController, UIReferenceLibraryViewController *);
TF_EC_MINSTANCE_IMP(UIReferenceLibraryViewController, UIReferenceLibraryViewController *);






//superclass pros UIViewController
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,UITabBarItem *,tabBarItem)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,BOOL,hidesBottomBarWhenPushed)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,id<UIViewControllerTransitioningDelegate>  ,transitioningDelegate)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,UIView *,view)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,NSString *,title)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,BOOL,definesPresentationContext)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,BOOL,providesPresentationContextTransitionStyle)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,long long,modalTransitionStyle)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,long long,modalPresentationStyle)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,BOOL,modalPresentationCapturesStatusBarAppearance)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,BOOL,wantsFullScreenLayout)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,unsigned long long,edgesForExtendedLayout)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,BOOL,extendedLayoutIncludesOpaqueBars)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,BOOL,automaticallyAdjustsScrollViewInsets)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,CGSize,preferredContentSize)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,CGSize,contentSizeForViewInPopover)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,BOOL,modalInPopover)
//superclass pros UIResponder
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,NSUserActivity *,userActivity)
//superclass pros NSObject
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,NSArray *,accessibilityElements)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,NSArray *,accessibilityCustomActions)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,BOOL,isAccessibilityElement)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,NSString *,accessibilityLabel)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,NSString *,accessibilityHint)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,NSString *,accessibilityValue)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,unsigned long long,accessibilityTraits)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,UIBezierPath *,accessibilityPath)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,CGPoint,accessibilityActivationPoint)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,NSString *,accessibilityLanguage)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,BOOL,accessibilityElementsHidden)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,BOOL,accessibilityViewIsModal)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,BOOL,shouldGroupAccessibilityChildren)
TF_EC_CHAIN_PROP_IMP(UIReferenceLibraryViewController ,long long,accessibilityNavigationStyle)





@end